name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java (required for Android SDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          android-sdk-version: 'commandlinetools;latest'

      # Step 4: Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      # Step 5: Install necessary SDK packages
      - name: Install build tools, platform tools, and platforms
        run: |
          sdkmanager "build-tools;36.0.0" "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64"

      # Step 6: Install any additional dependencies if required (e.g., Buildozer)
      - name: Install Buildozer
        run: |
          pip install buildozer

      # Step 7: Build APK using Buildozer (or other tool of choice)
      - name: Build APK
        run: |
          buildozer android debug
          
      # Step 8: (Optional) Upload the APK if the build is successful
      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-android-apk
          path: bin/*.apk

