name: 'Kivy App to APK'
description: 'Build and release Android APK from Kivy application'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: 'x64'
          
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip python3-pip \
            autoconf libtool pkg-config zlib1g-dev libncurses-dev \
            cmake libffi-dev libssl-dev
            
      # Use your existing buildozer.spec instead of creating a new one
            
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade Cython==0.29.33 virtualenv
          python -m pip install --upgrade buildozer
          
      # Add this to avoid SSL verification issues
      - name: Configure Git for https connections
        run: |
          git config --global http.sslVerify false
          
      - name: Build with Buildozer
        run: |
          export GIT_HTTP_LOW_SPEED_LIMIT=1000
          export GIT_HTTP_LOW_SPEED_TIME=300
          buildozer android debug -v
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
          if-no-files-found: error
