name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ccache \
          git \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          zlib1g-dev \
          libncursesw5-dev \
          libbz2-dev \
          libgdbm-dev \
          liblzma-dev \
          libreadline-dev \
          libgdbm-compat-dev \
          openssl \
          bzip2 \
          uuid-dev \
          libnss3 \
          libx11-dev \
          python3-pip

        python3 -m pip install --upgrade pip
        pip install --user buildozer cython

    - name: Cache .buildozer
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Build APK
      run: |
        export PATH=$HOME/.local/bin:$PATH
        buildozer android debug android
      env:
        ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk

    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true
      env:
        ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: ./bin/*.apk
